#!/bin/sh

cd ~/RS/flight_test/pipeline/

#run mpileup to pile the mapped data into one sync file

samtools faidx ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa

# split BAM into chromosomes of interest and index them.
# NOTE: you can also extract information for your mitochondrial DNA which name is mtDNA_65039429

samtools index -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam &&\

# NOTE: for samtools version 1.9. Index your Bam file (create bai file) before split.
# Otherwise you will get "[main_samview] random alignment retrieval only works for indexed BAM or CRAM files."
# message (added by Bilal Basdag 03.02.2020)

samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam 2L > ../data/F30/Pool_311.F30r11sub1_2L.bam &&\
samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam 2R > ../data/F30/Pool_311.F30r11sub1_2R.bam &&\
samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam 3L > ../data/F30/Pool_311.F30r11sub1_3L.bam &&\
samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam 3R > ../data/F30/Pool_311.F30r11sub1_3R.bam &&\
samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam 4 > ../data/F30/Pool_311.F30r11sub1_4.bam &&\
samtools view -b /Users/ychen/RS/flight_test/data/F30/LB_311.TI02.bam X > ../data/F30/Pool_311.F30r11sub1_X.bam &&\

samtools index ../data/F30/Pool_311.F30r11sub1_2L.bam &&\
samtools index ../data/F30/Pool_311.F30r11sub1_2R.bam &&\
samtools index ../data/F30/Pool_311.F30r11sub1_3L.bam &&\
samtools index ../data/F30/Pool_311.F30r11sub1_3R.bam &&\
samtools index ../data/F30/Pool_311.F30r11sub1_4.bam &&\
samtools index ../data/F30/Pool_311.F30r11sub1_X.bam &&\

samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_2L.bam > ../data/F30/Pool_311.F30r11sub1_2L.pileup &&\
samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_2R.bam > ../data/F30/Pool_311.F30r11sub1_2R.pileup &&\
samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_3L.bam > ../data/F30/Pool_311.F30r11sub1_3L.pileup &&\
samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_3R.bam > ../data/F30/Pool_311.F30r11sub1_3R.pileup &&\
samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_4.bam > ../data/F30/Pool_311.F30r11sub1_4.pileup &&\
samtools mpileup -B -q 20 -Q 0 -f ~/RS/flight_test/data/reference/dsimM252v1.2+microbiome.fa ../data/F30/Pool_311.F30r11sub1_X.bam > ../data/F30/Pool_311.F30r11sub1_X.pileup &&\

# concate all the files into one 
cd ../data/F30/
cat Pool_311.F30r11sub1_2L.pileup Pool_311.F30r11sub1_2R.pileup Pool_311.F30r11sub1_3L.pileup Pool_311.F30r11sub1_3R.pileup Pool_311.F30r11sub1_4.pileup Pool_311.F30r11sub1_X.pileup > Pool_311.F30r11sub1_allChr.pileup
