#!/bin/sh
# to filter the SNPs piled up in our mapped data based on Neda's SNP set.
# this awk command line is from Sheng-kai

cd /Users/ychen/RS/flight_test/data/F30

awk 'BEGIN{OFS="\t"} NR==FNR {f1[$1$2] = $0; next} ($1$2 in f1) {print $0}' \
../reference/Dsim_base_F60_bam.sorted.rmdup.filter.mpileup.Q20.polymorphic_indel_repeat_Ytranslocremoved_masked_MajorChr.sync_furthermasked.cmh  \
./Pool_311.F30r11sub1_all_chr.sync > \
./Pool_311.F30r11sub1_all_chr_Neda_filtered.sync
